services:
  testapp_con:
    image: security_img
    container_name: my_testapp_con  # Nouveau nom de conteneur
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/komita
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ghofrane
    depends_on:
      - db
    restart: always

  db:
    ports:
      - "5432:5432"
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=komita
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ghofrane
    volumes:
      - C:\postgres_container_komita:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: testapp_con
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/komita
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ghofrane
    depends_on:
      - db
    restart: always
