server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://dpg-cs2sq3dsvqrc73dq0uhg-a.oregon-postgres.render.com:5432/komita
    username: komita_user
    password: MRaxOD8WEENdSFxAdyPPCISph9LXmkss
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      search:
        default:
          directory_provider: filesytem
          indexBase: /data/index/default
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
mail:
  host: smtp.gmail.com
  port: 587
  username: bouthainabenhamida@gmail.com
  password: pkmj tsup moqy rdjy
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
