server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://dpg-ctgukb23esus73ac3eag-a.oregon-postgres.render.com/komita_r5gd
    username: komita_r5gd_user
    password: CaBHQFALLOcT8Wr3jy8kTeIM1OxQjzow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      search:
        default:
          directory_provider: filesytem
          indexBase: /data/index/default
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
mail:
  host: smtp.gmail.com
  port: 587
  username: bouthainabenhamida@gmail.com
  password: pkmj tsup moqy rdjy
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  
